name: Build and Deploy Java Web App to Tomcat

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to Tomcat
        env:
          TOMCAT_HOST: ${{ secrets.TOMCAT_HOST }}
          TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
        run: |
          curl -u $TOMCAT_USER:$TOMCAT_PASSWORD --upload-file target/vottingApplication.war "http://$TOMCAT_HOST:8080/manager/text/deploy?path=/vottingApplication&update=true"
